- paths:
    - log-generator\src\LogGenerator\logs\*.log
  fields:
    env: dev
    logtype: log4net
  fields_under_root: true
  #tags: ["test"]
  multiline.pattern: '^20[0-9]{2}-[01][0-9]-[0123][0-9]'
  multiline.negate: true
  multiline.match: after
  ignore_older: 0